/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Temp_Converter;

/**
 *
 * @author YOUNIS-J
 */
public class Main_File extends javax.swing.JFrame {

    /**
     * Creates new form Temprature_Converter
     */
    public Main_File() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cel_to_Far = new javax.swing.JButton();
        btn_cel_to_kal = new javax.swing.JButton();
        btn_far_to_cel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_cel_to_Far.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        btn_cel_to_Far.setText("Celcius To Fahrenheit");
        btn_cel_to_Far.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cel_to_FarActionPerformed(evt);
            }
        });

        btn_cel_to_kal.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        btn_cel_to_kal.setText("Celcius To Kelvin");
        btn_cel_to_kal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cel_to_kalActionPerformed(evt);
            }
        });

        btn_far_to_cel.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        btn_far_to_cel.setText("Fahrenheit To Celcius");
        btn_far_to_cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_far_to_celActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_far_to_cel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cel_to_kal, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cel_to_Far, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_cel_to_Far, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_far_to_cel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_cel_to_kal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cel_to_FarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cel_to_FarActionPerformed
        // TODO add your handling code here:
        new Celcius_To_Farenheit().setVisible(true);
    }//GEN-LAST:event_btn_cel_to_FarActionPerformed

    private void btn_far_to_celActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_far_to_celActionPerformed
        // TODO add your handling code here:
        new Farhenheit_To_Celcius().setVisible(true);
    }//GEN-LAST:event_btn_far_to_celActionPerformed

    private void btn_cel_to_kalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cel_to_kalActionPerformed
        // TODO add your handling code here:
        new Celcius_To_Kelvin().setVisible(true);
    }//GEN-LAST:event_btn_cel_to_kalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_File().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cel_to_Far;
    private javax.swing.JButton btn_cel_to_kal;
    private javax.swing.JButton btn_far_to_cel;
    // End of variables declaration//GEN-END:variables
}
